version: 1
setup:
  - run: helm registry install quay.io/giantswarm/cert-operator-lab-chart -- -n cert-operator-lab --set imageTag=latest --set clusterName=my-cluster --wait
    waitFor:
      run: kubectl get certificate
      match: No resources found\.

  - run: helm registry install quay.io/giantswarm/cert-resource-lab-chart -- -n cert-resource-lab --set clusterName=my-cluster
    waitFor:
      run: kubectl get secrets
      match: my-cluster-api\s*Opaque

inClusterTest:
  enabled: true

teardown:
  - run: helm delete cert-resource-lab --purge
  - run: helm delete cert-operator-lab --purge
